In [44]:
import pandas as pd
import random

# from google.colab import drive

# DB FIX Crime

## Agregar Datos Faltantes al Dataset

MONTAJE DE ARCHIVOS GOOGLE DRIVE:

In [45]:
# drive.mount('/content/drive')

* Dataframe Hoteles

In [46]:
# hoteles_dataset_content = '/content/drive/MyDrive/Colab Notebooks/HotelWiseML/hoteles_unificado.parquet'
# hoteles_dataset = pd.read_parquet(hoteles_dataset_content)

* Dataframe Seguridad

In [47]:
# crime_df_content = '/content/drive/MyDrive/Colab Notebooks/HotelWiseML/CrimeInTheUSA.parquet'
# crime_df_dataset = pd.read_parquet(crime_df_content)

MONTAJE DE ARCHIVOS LOCAL:

* Dataframe Hoteles

In [48]:
hoteles_dataset_content = 'hoteles_unificado.parquet'
hoteles_dataset = pd.read_parquet(hoteles_dataset_content)

* Dataframe Seguridad

In [49]:
crime_df_content = "Crime_In_The_USA/CrimeInTheUSA.parquet"
crime_df_dataset = pd.read_parquet(crime_df_content)

In [50]:
hoteles_dataset.head(2)

,NAME,LATITUDE,LONGITUDE,CITY,COUNTY,STATE,TEXT,AVG_RATING,AMENITIES
0,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,I'm new to the area and needed a place to live...,2.8,"[Car Rental, Pet-Friendly, 24-Hour Reception, ..."
1,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,This was previously a Ramada but was sold & be...,2.8,"[Fitness Center, Currency Exchange, Room Servi..."

In [51]:
crime_df_dataset.head(2)

     STATE        CITY  POPULATION  TOTAL CRIME  CRIME RATE
0  ALABAMA   Abbeville      2551.0        134.0       52.53
1  ALABAMA  Adamsville      4323.0        616.0      142.49

## Combinación db Hoteles con db Seguridad

In [52]:
# Realizar la fusión
hoteles_final = pd.merge(hoteles_dataset, crime_df_dataset[['STATE', 'CITY', 'CRIME RATE']], 
                         left_on=[hoteles_dataset['STATE'].str.lower(), hoteles_dataset['CITY'].str.lower()], 
                         right_on=[crime_df_dataset['STATE'].str.lower(), crime_df_dataset['CITY'].str.lower()], 
                         how='left')

# Eliminar las columnas adicionales
hoteles_final.drop(['key_0', 'key_1', 'CITY_y', 'STATE_y'], axis=1, inplace=True)
hoteles_final.rename(columns={'CITY_x': 'CITY', 'STATE_x': 'STATE'}, inplace=True)

In [53]:
hoteles_final.head(2)

,NAME,LATITUDE,LONGITUDE,CITY,COUNTY,STATE,TEXT,AVG_RATING,AMENITIES,CRIME RATE
0,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,I'm new to the area and needed a place to live...,2.8,"[Car Rental, Pet-Friendly, 24-Hour Reception, ...",112.26
1,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,This was previously a Ramada but was sold & be...,2.8,"[Fitness Center, Currency Exchange, Room Servi...",112.26

###  Guardamos el df con las columnas necesarias para el análisis posterior

In [54]:
hoteles_para_guardar=hoteles_final[['NAME','LATITUDE','LONGITUDE','CITY','COUNTY', 'STATE', 'TEXT','AVG_RATING','CRIME RATE', 'AMENITIES']]

In [55]:
hoteles_para_guardar.rename(columns={'TEXT': 'REVIEWS','CRIME RATE':'CRIME_RATE'}, inplace=True)

In [56]:
hoteles_para_guardar.head(2)

,NAME,LATITUDE,LONGITUDE,CITY,COUNTY,STATE,REVIEWS,AVG_RATING,CRIME_RATE,AMENITIES
0,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,I'm new to the area and needed a place to live...,2.8,112.26,"[Car Rental, Pet-Friendly, 24-Hour Reception, ..."
1,Palms Inn,28.510625,-81.418326,Orlando,Orange County,Florida,This was previously a Ramada but was sold & be...,2.8,112.26,"[Fitness Center, Currency Exchange, Room Servi..."

In [57]:
len(hoteles_para_guardar)

439

In [58]:
celdas_vacias = hoteles_para_guardar['CRIME_RATE'].isna().sum()
print("Número de celdas vacías en la columna CRIME_RATE:", celdas_vacias)

Número de celdas vacías en la columna CRIME_RATE: 0

In [59]:
# Guardar DataFrame en un archivo Parquet
hoteles_para_guardar.to_parquet('hoteles_unificado_final.parquet')